name: Caller Workflow

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  call-example:
    uses: ./.github/workflows/receiver.yml
    with:
      message: "Hello from caller 👋"
      branch: ${{ github.ref_name }}
