on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello from caller
        run: echo "Hello from caller.yml 👋"

      - name: Trigger receiver workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d "{\"event_type\": \"trigger-receiver\", \"client_payload\": {\"ref\": \"$BRANCH\"}}"
