name: Caller Workflow

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say hello from caller
        run: echo "Hello from caller.yml 👋"

      - name: Trigger "Receiver Workflow" workflow
        run: |
          gh workflow run "Receiver Workflow" \
            --ref ${{ github.head_ref }} \
            --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
