name: Receiver Workflow

on:
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Do some work
        run: |
          echo "Receiver workflow is running..."
          sleep 5
          echo "Receiver workflow finished work."

      - name: Call Caller workflow again
        run: |
          echo "Triggering Caller workflow to continue..."
          gh workflow run "Caller Workflow" \
            --ref ${{ github.head_ref }} \
            --repo ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
