name: Receiver Workflow

on:
  workflow_call:
    inputs:
      message:
        description: "Message to display"
        required: true
        type: string
      branch:
        description: "Branch name"
        required: true
        type: string

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo received message and branch
        run: |
          echo "Message: ${{ inputs.message }}"
          echo "Branch: ${{ inputs.branch }}"
