name: PR Slack Integration

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack about PR
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: 'C09D2BV45PS'
          slack-message: |
            :bell: *New PR Created*: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>
            *Author*: ${{ github.event.pull_request.user.login }}
            *Reviewers*: ${{ join(github.event.pull_request.requested_reviewers.*.login, ', ') }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
