name: PR Slack Thread Integration

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pr-opened:
    if: github.event.action == 'opened' || github.event.action == 'reopened'
    runs-on: ubuntu-latest
    steps:
      - name: Send new PR message to Slack
        id: slack_msg
        run: |
          RESPONSE=$(curl -s -X POST \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H "Content-type: application/json" \
            --data "{\"channel\":\"C09D2BV45PS\",\"text\":\":bell: *New PR*: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\n*Author*: ${{ github.event.pull_request.user.login }}\n*Reviewers*: ${{ join(github.event.pull_request.requested_reviewers.*.login, ', ') }}\"}" \
            https://slack.com/api/chat.postMessage)
          TS=$(echo $RESPONSE | jq -r '.ts')
          echo "THREAD_TS=$TS" >> $GITHUB_ENV
      - name: Save thread_ts artifact
        run: |
          mkdir -p ./thread
          echo "$THREAD_TS" > ./thread/thread_ts.txt
      - name: Upload thread_ts artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-${{ github.event.pull_request.number }}-thread
          path: ./thread

  pr-updated:
    if: github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - name: Download thread_ts artifact
        uses: actions/download-artifact@v4
        with:
          name: pr-${{ github.event.pull_request.number }}-thread
          path: ./thread
        continue-on-error: true

      - name: Read thread_ts
        id: read_thread
        run: |
          if [ -f ./thread/thread_ts.txt ]; then
            echo "THREAD_TS=$(cat ./thread/thread_ts.txt)" >> $GITHUB_ENV
          else
            echo "THREAD_TS=" >> $GITHUB_ENV
          fi

      - name: Send update to Slack thread
        run: |
          if [ -n "$THREAD_TS" ]; then
            curl -s -X POST \
              -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
              -H "Content-type: application/json" \
              --data "{\"channel\":\"C09D2BV45PS\",\"text\":\":arrow_up: PR Update: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>\",\"thread_ts\":\"$THREAD_TS\"}" \
              https://slack.com/api/chat.postMessage
          else
            echo "No THREAD_TS found, skipping."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
